/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TemplatesImport } from './routes/templates'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as UploadIndexImport } from './routes/upload/index'
import { Route as RunNewImport } from './routes/run/new'

// Create/Update Routes

const TemplatesRoute = TemplatesImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UploadIndexRoute = UploadIndexImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => rootRoute,
} as any)

const RunNewRoute = RunNewImport.update({
  id: '/run/new',
  path: '/run/new',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesImport
      parentRoute: typeof rootRoute
    }
    '/run/new': {
      id: '/run/new'
      path: '/run/new'
      fullPath: '/run/new'
      preLoaderRoute: typeof RunNewImport
      parentRoute: typeof rootRoute
    }
    '/upload/': {
      id: '/upload/'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/templates': typeof TemplatesRoute
  '/run/new': typeof RunNewRoute
  '/upload': typeof UploadIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/templates': typeof TemplatesRoute
  '/run/new': typeof RunNewRoute
  '/upload': typeof UploadIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/templates': typeof TemplatesRoute
  '/run/new': typeof RunNewRoute
  '/upload/': typeof UploadIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/templates' | '/run/new' | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/templates' | '/run/new' | '/upload'
  id: '__root__' | '/' | '/about' | '/templates' | '/run/new' | '/upload/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  TemplatesRoute: typeof TemplatesRoute
  RunNewRoute: typeof RunNewRoute
  UploadIndexRoute: typeof UploadIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  TemplatesRoute: TemplatesRoute,
  RunNewRoute: RunNewRoute,
  UploadIndexRoute: UploadIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/templates",
        "/run/new",
        "/upload/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/templates": {
      "filePath": "templates.tsx"
    },
    "/run/new": {
      "filePath": "run/new.tsx"
    },
    "/upload/": {
      "filePath": "upload/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
